[project]
name = "marspec"
version = "0.1.0"
description = ""
requires-python = ">=3.13"
dependencies = [
    "streamlit>=1.57.0",
    "numpy>=2.4.4",
    "plotly>=6.7.0",
    "matplotlib>=3.10.9",
    "eqsig>=1.2.17",
]

[tool.uv]
package = false

[tool.pyright]
# https://github.com/microsoft/pyright/blob/main/docs/configuration.md
useLibraryCodeForTypes = true
exclude = [".cache"]

[tool.ruff]
# https://beta.ruff.rs/docs/configuration/
select = ['E', 'W', 'F', 'I', 'B', 'C4', 'ARG', 'SIM']
ignore = ['W291', 'W292', 'W293']